name: Zig JWT CI

on:
  merge_group:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test_alpine:
  runs-on: ubuntu-latest
  container:
    image: alpine
    options: --security-opt seccomp=unconfined
  steps:
    - name: Install dependencies
      run: |
        apk update
        apk add -U git openssl-dev gcc musl-dev
    - run: git config --system --add safe.directory '*'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: chmod +x ./zig/download.sh
    - run: ./zig/download.sh latest
    - run: ./zig/zig build test

  test_ubuntu:
    strategy:
      matrix:
        include:

          - { os: 'ubuntu-latest' }
         

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - run: chmod +x ./zig/download.sh
      - run: ./zig/download.sh latest
      - run: ./zig/zig build test


  test_windows:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

        
      - run: winget install -e --id OpenSSL.OpenSSL
        shell: pwsh

      - run: .\zig\download.bat latest
        shell: cmd
      - run: .\zig\zig build test

  test_macos:

    strategy:
      matrix:
        include:
          - { os: 'macos-latest' }
          - { os: 'macos-13' }
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: brew update && brew install openssl
      - run: chmod +x ./zig/download.sh
      - run: ./zig/download.sh latest
      - run: ./zig/zig build test

