name: Zig JWT CI

on:
  merge_group:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --security-opt seccomp=unconfined
    steps:
      - name: Install dependencies
        run: |
          apk update

          apk add -U git openssl-dev gcc musl-dev cmake  make perl linux-headers
      - name: Configure Git
        run: git config --system --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build OpenSSL from source
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl
          perl -v
          ./config --prefix=/usr/local --openssldir=/usr/local/ssl

          make -j$(nproc)
          make install

      - name: Setup Zig
        run: |

          chmod +x ./zig/download.sh

          ./zig/download.sh latest
      - name: Build and test
        run: ./zig/zig build test

  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Setup Zig
        run: |
          chmod +x ./zig/download.sh
          ./zig/download.sh latest
      - name: Build and test

        run: ./zig/zig build test


  test_windows:
    runs-on: windows-latest
    steps:
      - name: Configure Git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

        with:
          fetch-depth: 0
      - name: Install OpenSSL
        shell: pwsh
        run: |

        $url = "https://slproweb.com/download/Win64OpenSSL-3_1_4.msi"
        Invoke-WebRequest -Uri $url -OutFile openssl.msi
        Start-Process msiexec -ArgumentList "/i openssl.msi /quiet /qn /norestart" -Wait
        Remove-Item openssl.msi
        

       
        $env:OPENSSL_DIR = "${env:ProgramFiles}\OpenSSL-Win64"
        echo "OPENSSL_DIR=$env:OPENSSL_DIR" >> $env:GITHUB_ENV
        echo "${env:ProgramFiles}\OpenSSL-Win64\bin" >> $env:GITHUB_PATH
        
      
        Get-ChildItem "${env:ProgramFiles}\OpenSSL-Win64\bin\libcrypto-3-x64.dll"
        $env:OPENSSL_DIR = "${env:ProgramFiles}\OpenSSL-Win64"
        echo "OPENSSL_DIR=$env:OPENSSL_DIR" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Setup Zig
        run: .\zig\download.bat latest
        shell: cmd
      - name: Build and test
        run: .\zig\zig build test

  test_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          brew update
          brew install openssl 
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig" >> $GITHUB_ENV
      - name: Setup Zig
        run: |
          chmod +x ./zig/download.sh
          ./zig/download.sh latest
      - name: Build and test
        run: ./zig/zig build test
